name: Python Backup Script Check

on:
  push:
    paths:
      - '**.py'

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 backup.py
